CREATE TABLE talks (
  id SERIAL PRIMARY KEY,
  slug VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  speaker_name VARCHAR NOT NULL,
  speaker_title VARCHAR NOT NULL,
  track VARCHAR NOT NULL,
  date TIMESTAMP WITH TIME ZONE
);
