# Generated by Django 5.1.4 on 2025-01-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
