services:
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: venue
      POSTGRES_USER: venue
      POSTGRES_PASSWORD: venue
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 1s
      start_interval: 1s
      start_period: 30s
      retries: 100
