# Generated by Django 5.0.6 on 2024-06-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.SlugField(default='hehe', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(upload_to='speakers'),
        ),
    ]
